apiVersion: v1
kind: Service
metadata:
  name: app-nodejs
  labels:
    app: app-nodejs
    monitoring: enabled
spec:
  type: ClusterIP
  selector:
    app: app-nodejs
  ports:
  - name: metrics 
    port: 3000
    targetPort: 3000
    protocol: TCP
