name: Build and Deploy app-nodejs
on:
  push:
    branches:
      - main

jobs:
  build:
    uses: wellingtonns/pipeline-template/.github/workflows/build-push.yml@main
    with:
      IMAGE_NAME: welignton/app-nodejs
      APP_NAME: app-nodejs
    secrets: inherit

  sync-argocd:
    needs: build
    uses: wellingtonns/pipeline-template/.github/workflows/argocd-sync.yml@main
    with:
      APP_NAME: app-nodejs
    secrets: inherit